// <auto-generated by `noemancer bindings csharp` />
namespace Noemancer.Generated;

public static class EngineSchema
{
    public const string ProtocolVersion = "0.2";

    public static class Components
    {
        public static readonly ComponentId AnimationPlayer = new("engine.component.AnimationPlayer");
        public static readonly ComponentId BoxCollider = new("engine.component.BoxCollider");
        public static readonly ComponentId Camera = new("engine.component.Camera");
        public static readonly ComponentId CapsuleCollider = new("engine.component.CapsuleCollider");
        public static readonly ComponentId ConvexHullCollider = new("engine.component.ConvexHullCollider");
        public static readonly ComponentId DirectionalLight = new("engine.component.DirectionalLight");
        public static readonly ComponentId LocalLight = new("engine.component.LocalLight");
        public static readonly ComponentId ManagedScript = new("engine.component.ManagedScript");
        public static readonly ComponentId MeshRenderer = new("engine.component.MeshRenderer");
        public static readonly ComponentId PbrMaterial = new("engine.component.PbrMaterial");
        public static readonly ComponentId RigidBody = new("engine.component.RigidBody");
        public static readonly ComponentId SphereCollider = new("engine.component.SphereCollider");
        public static readonly ComponentId SpriteRenderer = new("engine.component.SpriteRenderer");
        public static readonly ComponentId TilemapRenderer = new("engine.component.TilemapRenderer");
        public static readonly ComponentId Transform = new("engine.component.Transform");
        public static readonly ComponentId Velocity = new("engine.component.Velocity");
    }

    public static class Properties
    {
        public static class AnimationPlayer
        {
            public static readonly PropertyId<AssetId> AnimationGraphAsset = new("engine.entity.animation.animationGraphAsset");
            public static readonly PropertyId<AssetId> ClipAsset = new("engine.entity.animation.clipAsset");
            public static readonly PropertyId<bool> Looping = new("engine.entity.animation.looping");
            public static readonly PropertyId<AssetId> NextClipAsset = new("engine.entity.animation.nextClipAsset");
            public static readonly PropertyId<float> PlaybackSpeed = new("engine.entity.animation.playbackSpeed");
            public static readonly PropertyId<bool> Playing = new("engine.entity.animation.playing");
            public static readonly PropertyId<string> RootMotionMode = new("engine.entity.animation.rootMotionMode");
            public static readonly PropertyId<AssetId> StateMachineAsset = new("engine.entity.animation.stateMachineAsset");
            public static readonly PropertyId<float> TransitionDuration = new("engine.entity.animation.transitionDuration");
        }

        public static class BoxCollider
        {
            public static readonly PropertyId<Float3> HalfExtents = new("engine.entity.collider.halfExtents");
        }

        public static class CapsuleCollider
        {
            public static readonly PropertyId<float> HalfHeight = new("engine.entity.collider.halfHeight");
        }

        public static class Collider
        {
            public static readonly PropertyId<float> Friction = new("engine.entity.collider.friction");
            public static readonly PropertyId<bool> IsTrigger = new("engine.entity.collider.isTrigger");
            public static readonly PropertyId<float> Restitution = new("engine.entity.collider.restitution");
        }

        public static class LocalLight
        {
            public static readonly PropertyId<Color3> Color = new("engine.entity.localLight.color");
            public static readonly PropertyId<Float3> Direction = new("engine.entity.localLight.direction");
            public static readonly PropertyId<float> InnerConeDegrees = new("engine.entity.localLight.innerConeDegrees");
            public static readonly PropertyId<string> Kind = new("engine.entity.localLight.kind");
            public static readonly PropertyId<float> LuminousPowerLumens = new("engine.entity.localLight.luminousPowerLumens");
            public static readonly PropertyId<float> OuterConeDegrees = new("engine.entity.localLight.outerConeDegrees");
            public static readonly PropertyId<float> RangeMeters = new("engine.entity.localLight.rangeMeters");
            public static readonly PropertyId<float> SourceRadiusMeters = new("engine.entity.localLight.sourceRadiusMeters");
        }

        public static class ManagedScript
        {
            public static readonly PropertyId<AssetId> AssemblyAsset = new("engine.entity.managedScript.assemblyAsset");
            public static readonly PropertyId<bool> Enabled = new("engine.entity.managedScript.enabled");
            public static readonly PropertyId<System.Text.Json.JsonElement> PropertiesJson = new("engine.entity.managedScript.properties");
            public static readonly PropertyId<string> TypeName = new("engine.entity.managedScript.typeName");
        }

        public static class PbrMaterial
        {
            public static readonly PropertyId<Color3> BaseColor = new("engine.entity.material.baseColor");
            public static readonly PropertyId<Color3> EmissiveColor = new("engine.entity.material.emissiveColor");
            public static readonly PropertyId<float> EmissiveIntensity = new("engine.entity.material.emissiveIntensity");
            public static readonly PropertyId<float> Metallic = new("engine.entity.material.metallic");
            public static readonly PropertyId<float> Roughness = new("engine.entity.material.roughness");
        }

        public static class RigidBody
        {
            public static readonly PropertyId<bool> AllowSleeping = new("engine.entity.rigidBody.allowSleeping");
            public static readonly PropertyId<float> AngularDamping = new("engine.entity.rigidBody.angularDamping");
            public static readonly PropertyId<bool> ContinuousCollision = new("engine.entity.rigidBody.continuousCollision");
            public static readonly PropertyId<float> GravityFactor = new("engine.entity.rigidBody.gravityFactor");
            public static readonly PropertyId<float> LinearDamping = new("engine.entity.rigidBody.linearDamping");
            public static readonly PropertyId<float> Mass = new("engine.entity.rigidBody.mass");
            public static readonly PropertyId<string> MotionType = new("engine.entity.rigidBody.motionType");
        }

        public static class SphereCollider
        {
            public static readonly PropertyId<float> Radius = new("engine.entity.collider.radius");
        }

        public static class SpriteRenderer
        {
            public static readonly PropertyId<string> Clip = new("engine.entity.sprite.clip");
            public static readonly PropertyId<bool> FlipX = new("engine.entity.sprite.flipX");
            public static readonly PropertyId<bool> FlipY = new("engine.entity.sprite.flipY");
            public static readonly PropertyId<float> PlaybackSpeed = new("engine.entity.sprite.playbackSpeed");
            public static readonly PropertyId<bool> Playing = new("engine.entity.sprite.playing");
            public static readonly PropertyId<string> SortingLayer = new("engine.entity.sprite.sortingLayer");
            public static readonly PropertyId<int> SortingOrder = new("engine.entity.sprite.sortingOrder");
            public static readonly PropertyId<AssetId> SpriteAsset = new("engine.entity.sprite.spriteAsset");
            public static readonly PropertyId<bool> Visible = new("engine.entity.sprite.visible");
        }

        public static class TilemapRenderer
        {
            public static readonly PropertyId<bool> CollisionEnabled = new("engine.entity.tilemap.collisionEnabled");
            public static readonly PropertyId<AssetId> TilemapAsset = new("engine.entity.tilemap.tilemapAsset");
            public static readonly PropertyId<bool> Visible = new("engine.entity.tilemap.visible");
        }

        public static class Transform
        {
            public static readonly PropertyId<Float3> Position = new("engine.entity.transform.position");
            public static readonly PropertyId<Float3> RotationEulerDegrees = new("engine.entity.transform.rotationEulerDegrees");
            public static readonly PropertyId<Float3> Scale = new("engine.entity.transform.scale");
        }

        public static class Velocity
        {
            public static readonly PropertyId<Float3> Angular = new("engine.entity.velocity.angular");
            public static readonly PropertyId<Float3> Linear = new("engine.entity.velocity.linear");
        }
    }
}
